
# docker-compose.yml
version: '3.1'
services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: dockerfile
    container_name: "prometheus"
    hostname: "prometheus"
    ports:
      - "9091:9090"
    links:    
      - chintan-service

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    ports:
      - "3000:3000"
    links:
      - prometheus
  
  chintan-service:
    image:  chintan-springboot-prometheus
    container_name: "chintan-springboot-prometheus"
    hostname: "chintan-springboot-prometheus"
    ports:
      - "8080:8080"
      - "8081:8081"